# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_j35Dhq71JagUWozIlRbERnE92aZksG3
"""

from queue import PriorityQueue

f = open("input1.txt", mode = 'r')
o = open("output1.txt", mode = 'w')
count = 0
finished_task = []

test_cases = int(f.readline())
q = PriorityQueue()
for i in range(test_cases):
  n,m = map(int, f.readline().split())
  q.put((m,n))

finish_time = -1

while not q.empty():
  temp = q.get()
  start_time = temp[1]
  if start_time >= finish_time:
    finish_time = temp[0]
    finished_task.append((temp[1], temp[0]))
    count += 1

print(count, file = o)
for i in range(len(finished_task)):
  print(finished_task[i][0], end = " ", file = o)
  print(finished_task[i][1], file = o)

o.close()