# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_j35Dhq71JagUWozIlRbERnE92aZksG3
"""

f = open("input4.txt", mode = 'r')
o = open("output4.txt", mode = 'w')

n = -1
m = -1
num_list = []

while n != 0 and m!= 0:
  n,m = map(int, f.readline().split())
  num_list.append((n,m))

def square_num(a,b):
  count = 0
  for i in range(a,b+1):
    if i * i >= a and i * i <= b:
      count += 1
  return count

for i in range(len(num_list)-1):
  count = square_num(num_list[i][0], num_list[i][1])
  print(count, file = o)
  print(count)

o.close()