# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_j35Dhq71JagUWozIlRbERnE92aZksG3
"""

from queue import PriorityQueue

f = open("input2.txt", mode = 'r')
o = open("output2.txt", mode = 'w')
count = 0
finished_task = []
unfinished_task = []

q = PriorityQueue()
un_q = PriorityQueue()

test_cases, people = map(int, f.readline().split())

def task_finish(q):
  finish_time = -1

  while not q.empty():
    temp = q.get()
    start_time = temp[1]
    if start_time >= finish_time:
      finish_time = temp[0]
      finished_task.append((temp[1], temp[0]))
    else:
      unfinished_task.append(temp)

for i in range(test_cases):
  n,m = map(int, f.readline().split())
  q.put((m,n))

for i in range(people):
  task_finish(q)
  for j in range(len(unfinished_task)):
    q.put((unfinished_task[j]))
print(len(finished_task), file = o)

o.close()