# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_j35Dhq71JagUWozIlRbERnE92aZksG3
"""

from queue import PriorityQueue

f = open("input3.txt", mode = 'r')
o = open("output3.txt", mode = 'w')

number_of_task = int(f.readline())
task_length = f.readline().split()
call_sequence = f.readline()

q = PriorityQueue()
jack_q = PriorityQueue()

jack_task = []
jill_task = []
total_task = []

jack_time = 0
jill_time = 0

def task_select(call):
  if call == "J":
    temp = int(q.get())
    jack_task.append(temp)
    total_task.append(temp)
    jack_q.put(temp*-1)

  if call == "j":
    temp = int(jack_q.get())
    pos_temp = temp * -1
    jill_task.append(pos_temp)
    total_task.append(pos_temp)

for i in range(len(task_length)):
  q.put(task_length[i])

for i in range(len(call_sequence)):
  task_select(call_sequence[i])

for i in range(len(total_task)):
  print(total_task[i], end = "", file = o)

for i in range(len(total_task)):
  if call_sequence[i] == "J":
    jack_time = jack_time + total_task[i]
  else:
    jill_time = jill_time + total_task[i]

print("", file = o)
print("Jack will work for {} hours".format(jack_time), file = o)
print("Jill will work for {} hours".format(jill_time), file = o)

o.close()